// <auto-generated />
namespace Dashboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig_musteri_urun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_musteri_urun));
        
        string IMigrationMetadata.Id
        {
            get { return "202309071319557_mig_musteri_urun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
